In [15]:
# In machine learning and deep learning using "Squared error" is useful
#Going through the samples in ecamulated way is called "Epoch"
# 4 ways of finding the error in ML and DL : Mean absolute error , Mean squared error ,Total error (indivisual error is called "Loss"),Binary cross entopy
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [16]:
#Running a for loop array on two arrays in a parallel way "zip" function
#MAE without numpy
def mae(y_predicted,y_true):
  total_error = 0
  for yt , yp in zip(y_true,y_predicted):
      total_error += abs(yt - yp)
  print("Total error:",total_error)
  mae = total_error / len(y_true)
  print("MAE:",mae)
  return mae

In [17]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


0.5

In [18]:
# power of numpy in one function
np.mean(np.abs(y_predicted-y_true))

0.5

In [20]:
np.log([0.00000000000001])

array([-32.2361913])

In [24]:
eplison = 1e-15

In [25]:
#value near 0 cuz log(0) is undifined
y_predicted_new = [max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [27]:
#value near 1
y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [28]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [29]:
np.log(y_predicted)

<ipython-input-29-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [30]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844